"""Small fixtures for the self-test (device) and host tests.

The real fixture EPUB is generated by ``tools/prepare_assets.py`` into
``app/assets/selftest/`` (a 12-chapter Korean EPUB). When it is missing (host
tests before ``prepare_assets`` ran) ``build_tiny_epub`` writes a 3-chapter one
with ebooklib. Third-party packages are imported inside the functions only.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

KOREAN_SAMPLE = "그는 검을 뽑았다. 마왕성의 문이 천천히 열렸다."
ENGLISH_SAMPLE = "Glossarion self-test: tokens, EPUB, PDF and crypto."
#: Page size of ``build_manga_cbz`` (a small portrait manga page).
MANGA_PAGE_SIZE = (480, 720)


def selftest_assets_dir(assets_dir: Optional[Path]) -> Optional[Path]:
    if assets_dir is None:
        return None
    path = Path(assets_dir) / "selftest"
    return path if path.is_dir() else None


def find_selftest_epub(assets_dir: Optional[Path]) -> Optional[Path]:
    """The generated fixture EPUB in ``<assets>/selftest`` (prefers '*selftest*')."""
    directory = selftest_assets_dir(assets_dir)
    if directory is None:
        return None
    epubs = sorted(p for p in directory.glob("*.epub") if p.is_file())
    if not epubs:
        return None
    preferred = [p for p in epubs if "selftest" in p.name.lower()]
    return (preferred or epubs)[0]


def build_tiny_epub(path: Path, chapters: int = 3) -> Path:
    """Write a minimal Korean EPUB with ebooklib and return its path."""
    from ebooklib import epub

    book = epub.EpubBook()
    book.set_identifier("glossarion-selftest-tiny")
    book.set_title("글로사리온 자가진단")
    book.set_language("ko")
    book.add_author("Glossarion")
    items = []
    for index in range(1, chapters + 1):
        chapter = epub.EpubHtml(
            title=f"제{index}장",
            file_name=f"chapter{index:04d}.xhtml",
            lang="ko",
        )
        chapter.content = (
            f"<html><head><title>제{index}장</title></head><body>"
            f"<h1>제{index}장</h1><p>{KOREAN_SAMPLE}</p><p>{index}번째 단락.</p>"
            "</body></html>"
        )
        book.add_item(chapter)
        items.append(chapter)
    book.toc = tuple(items)
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav", *items]
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    epub.write_epub(str(path), book)
    return path


def build_tiny_pdf_bytes(pages: int = 2) -> bytes:
    """A small PDF made with PyMuPDF (text + a filled rectangle per page)."""
    import fitz  # PyMuPDF

    doc = fitz.open()
    try:
        for index in range(pages):
            page = doc.new_page(width=300, height=200)
            page.insert_text((24, 48), f"{ENGLISH_SAMPLE} p{index + 1}", fontsize=10)
            page.draw_rect(fitz.Rect(24, 80, 140, 140), color=(0.88, 0.56, 0.6), fill=(0.88, 0.56, 0.6))
        return doc.tobytes()
    finally:
        doc.close()


def manga_page_png(index: int, size: tuple = MANGA_PAGE_SIZE) -> bytes:
    """One manga page as PNG bytes (Pillow): a white page, a panel border, a speech bubble with
    dark "text" strokes and a page-number mark, so every page differs."""
    import io

    from PIL import Image, ImageDraw

    width, height = size
    image = Image.new("RGB", (width, height), (255, 255, 255))
    draw = ImageDraw.Draw(image)
    draw.rectangle((12, 12, width - 13, height - 13), outline=(0, 0, 0), width=4)
    left, top = width // 6, height // 6
    right, bottom = width - width // 6, height // 2
    draw.ellipse((left, top, right, bottom), fill=(255, 255, 255), outline=(0, 0, 0), width=3)
    for row in range(3):
        y = top + (bottom - top) * (row + 2) // 6
        draw.line((left + 40 + 8 * row, y, right - 40 - 8 * row, y), fill=(20, 20, 20), width=6)
    for mark in range(int(index)):
        x = 30 + mark * 24
        draw.rectangle((x, height - 60, x + 14, height - 40), fill=(0, 0, 0))
    out = io.BytesIO()
    image.save(out, format="PNG")
    return out.getvalue()


def build_manga_cbz(path: Path, pages: int = 3) -> Path:
    """A CBZ (ZIP of ``001.png`` ... ) of ``pages`` manga pages (the U8 manga E2E input)."""
    import zipfile

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
        for index in range(1, int(pages) + 1):
            archive.writestr(f"{index:03d}.png", manga_page_png(index))
    return path


def scratch_dir(base: Optional[Path] = None) -> Path:
    """A writable scratch dir for the self-test (``<temp>/glossarion-selftest``)."""
    root = Path(base) if base is not None else Path(os.environ.get("TMPDIR") or os.environ.get("TEMP") or ".")
    path = root / "glossarion-selftest"
    path.mkdir(parents=True, exist_ok=True)
    return path
