"""Shared target-language options used by Glossarion interfaces."""


# Keep this list display-oriented: the selected text is also inserted into AI
# prompts, so human-readable language names are preferable to locale codes.
TARGET_LANGUAGES = (
    "English",
    "Spanish",
    "French",
    "German",
    "Italian",
    "Portuguese",
    "Russian",
    "Arabic",
    "Hindi",
    "Bengali",
    "Urdu",
    "Marathi",
    "Punjabi",
    "Gujarati",
    "Tamil",
    "Telugu",
    "Kannada",
    "Malayalam",
    "Nepali",
    "Sinhala",
    "Chinese",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Japanese",
    "Korean",
    "Turkish",
    "Azerbaijani",
    "Kazakh",
    "Uzbek",
    "Vietnamese",
    "Bahasa Indonesia",
    "Malay",
    "Filipino",
    "Thai",
    "Burmese",
    "Khmer",
    "Lao",
    "Dutch",
    "Polish",
    "Ukrainian",
    "Persian",
    "Hebrew",
    "Greek",
    "Romanian",
    "Swedish",
    "Czech",
    "Catalan",
    "Bulgarian",
    "Croatian",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Hungarian",
    "Danish",
    "Finnish",
    "Norwegian",
    "Swahili",
    "Afrikaans",
    "Amharic",
    "Hausa",
    "Yoruba",
    "Zulu",
)
