# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

# Add all your python files here
added_files = [
    ('translator_gui.py', '.'),
    ('splash_utils.py', '.'),
    ('TransateKRtoEN.py', '.'),
    ('extract_glossary_from_epub.py', '.'),
    ('extract_glossary_from_txt.py', '.'),     # NEW - Added TXT glossary extraction
    ('epub_converter.py', '.'),
    ('txt_processor.py', '.'),                  # NEW - Added TXT file processor
    ('scan_html_folder.py', '.'),
    ('unified_api_client.py', '.'),
    ('chapter_splitter.py', '.'),
    ('history_manager.py', '.'),
    ('image_translator.py', '.'),
    ('check_epub_directory.py', '.'),
    ('direct_imports.py', '.'),
    ('Halgakos.ico', '.'),  # Include icon
]

a = Analysis(
    ['translator_gui.py'],
    pathex=[],
    binaries=[],
    datas=added_files,
    hiddenimports=[
        # Core modules
        'TransateKRtoEN',
        'extract_glossary_from_epub',
        'extract_glossary_from_txt',     # NEW - Added TXT glossary extraction
        'epub_converter',
        'txt_processor',                 # NEW - Added TXT file processor
        'scan_html_folder',
        'unified_api_client',
        'chapter_splitter',
        'history_manager',
        'image_translator',
        'check_epub_directory',
        'direct_imports',
        'splash_utils',
        
        # EPUB/Text processing
        'ebooklib',
        'ebooklib.epub',
        'ebooklib.utils',
        'bs4',
        'BeautifulSoup',
        'soupsieve',
        'lxml',
        'lxml.etree',
        'lxml._elementpath',
        'lxml.html',
        'lxml.html.clean',
        'html5lib',
        'html',
        'html.parser',
        'cgi',
        
        # GUI
        'ttkbootstrap',
        'ttkbootstrap.constants',
        'tkinter',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'tkinter.simpledialog',
        'tkinter.ttk',
        '_tkinter',
        
        # PIL/Pillow - Image Processing
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageEnhance',
        'PIL.ImageFilter',
        'PIL.ImageOps',
        'PIL.ImageChops',
        'PIL.ImageStat',
        'PIL.ImagePalette',
        'PIL._binary',
        'PIL._imaging',
        'PIL._imagingft',
        'PIL._imagingmath',
        'PIL._imagingtk',
        'PIL.BmpImagePlugin',
        'PIL.GifImagePlugin',
        'PIL.JpegImagePlugin',
        'PIL.PngImagePlugin',
        'PIL.PpmImagePlugin',
        'PIL.TiffImagePlugin',
        'PIL.WebPImagePlugin',
        'PIL.IcoImagePlugin',
        'PIL.MicImagePlugin',
        'olefile',
        
        # AI/API clients
        'google',
        'google.generativeai',
        'google.ai',
        'google.ai.generativelanguage',
        'google.auth',
        'google.auth.transport',
        'google.auth.transport.requests',
        'openai',
        'tiktoken',
        'tiktoken_ext',
        'tiktoken_ext.openai_public',
        'regex',
		
		# Time/Date handling
        'tzdata',
        'zoneinfo',
        '_zoneinfo',
        'pytz',
        
        # Text processing
        'langdetect',
        'langdetect.detector',
        'langdetect.lang_detect_exception',
        'difflib',
        'unicodedata',
        
        # Progress/UI
        'tqdm',
        'tqdm.auto',
        'tqdm.std',
        
        # Network
        'requests',
        'requests.adapters',
        'requests.models',
        'requests.sessions',
        'chardet',
        'certifi',
        'urllib3',
        'urllib',
        'urllib.parse',
        'urllib.request',
        'idna',
        'ssl',
        'socket',
        'six',
        
        # Additional commonly missed modules
        'pkg_resources',
        'pkg_resources._vendor',
        'encodings',
        'encodings.utf_8',
        'encodings.ascii',
        'encodings.latin_1',
        'encodings.cp1252',
        'encodings.utf_16',
        'encodings.utf_32',
        'codecs',
        
        # Standard library modules
        'json',
        'csv',
        'hashlib',
        'tempfile',
        'shutil',
        'threading',
        'queue',
        're',
        'zipfile',
        'mimetypes',
        'collections',
        'collections.abc',
        'io',
        'logging',
        'logging.handlers',
        'time',
        'datetime',
        'os',
        'os.path',
        'sys',
        'dataclasses',
        'typing',
        'typing_extensions',
        'argparse',
        'subprocess',
        'platform',
        'pathlib',
        'contextlib',
        'functools',
        'itertools',
        'warnings',
        'copy',
        'weakref',
        'locale',
        'struct',
        'base64',
        'hmac',
        'secrets',
        'uuid',
        'email',
        'email.utils',
        'http',
        'http.client',
        'xml',
        'xml.etree',
        'xml.etree.ElementTree',
        'atexit',
        'multiprocessing',
        'multiprocessing.freeze_support',
        'gc',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'pytest',
        'nose',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Glossarion v2.4.0',  # Updated version for TXT support
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='Halgakos.ico'
)
