"""Host runs of the device UI flows (``src/mobile/tests/flows.py``; U9 ``flet test`` layer).

The flows ``flet test android`` runs on the emulator (``src/mobile/tests/test_ui_*.py``) run here
against the real app on a fake Flet session with ``tests/host_tester.PyTester``: every key,
tooltip and label they use must exist, and the screens they walk through must behave. The
Android file picker is replaced by ``HostPicker`` (the device run drives DocumentsUI through adb).

The chat flow is the full one: Settings › Import from desktop (a config.json pointing at the
fake OpenAI server), a new chat, ＋ › Files with the 12-chapter self-test EPUB, Send, the job card
reaches Done, Migrate, Library › the book › Chapters (12 completed chapters).

Run from src/mobile:
    python -m pytest -p no:cacheprovider -W ignore -o console_output_style=classic tests_host/test_ui_flows.py
"""

from __future__ import annotations

import asyncio
import importlib.util
import os
import sys
from pathlib import Path

import pytest

MOBILE_DIR = Path(__file__).resolve().parents[1]
APP_DIR = MOBILE_DIR / "app"
TESTS_DIR = MOBILE_DIR / "tests"
for path in (APP_DIR, TESTS_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))


def _has(module: str) -> bool:
    try:
        return importlib.util.find_spec(module) is not None
    except (ImportError, ValueError):
        return False


pytestmark = pytest.mark.skipif(not (_has("flet") and _has("msgpack")), reason="flet/msgpack not installed")

_TB_SPEC = importlib.util.spec_from_file_location("_glossarion_tb_helpers_u9ui", Path(__file__).with_name("test_bootstrap.py"))
_TB = importlib.util.module_from_spec(_TB_SPEC)
_TB_SPEC.loader.exec_module(_TB)
storage = _TB.storage
app_env = _TB.app_env


def _foundations():
    spec = importlib.util.spec_from_file_location("_glossarion_tf_helpers_u9ui",
                                                  Path(__file__).with_name("test_ui_foundations.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


async def _host_driver(tf, files: dict, *, first_run: bool = False):
    from host_tester import HostPicker, PyTester
    from ui_driver import UiDriver

    _m, conn, session, page, app = await tf._start("android", first_run=first_run)
    picker = HostPicker(files)
    bridge = getattr(app, "files", None)
    if bridge is not None:
        bridge._get_picker = lambda: picker  # what the app's FilePicker service would answer

    async def back():
        views = list(page.views or [])
        if len(views) > 1:
            await session.dispatch_event(page._i, "view_pop", {"route": views[-1].route})

    tester = PyTester(session, page)
    driver = UiDriver(tester, picker=picker, back=back, poll_ms=100, log=lambda *_a: None)
    return app, tester, driver


def test_dump_home_tree_when_asked(app_env, capsys):
    """Debug aid: GLOSSARION_UI_DUMP=1 prints the home screen's keys / tooltips / texts."""
    if not os.environ.get("GLOSSARION_UI_DUMP"):
        pytest.skip("set GLOSSARION_UI_DUMP=1 to print the tree")
    tf = _foundations()

    async def scenario():
        app, tester, driver = await _host_driver(tf, {})
        try:
            await asyncio.sleep(0.5)
            with capsys.disabled():
                for row in tester.dump():
                    print(row)
        finally:
            app.jobs.close()
            await tf._stop(app)

    asyncio.run(scenario())


def test_smoke_navigation_and_selftest_flows(app_env):
    import flows

    tf = _foundations()

    async def scenario():
        app, tester, driver = await _host_driver(tf, {})
        try:
            assert await flows.dismiss_welcome(driver) is False  # a returning user
            await flows.smoke_navigation(driver)
            assert await flows.run_selftest(driver, timeout=30) == "PASS"
        finally:
            app.jobs.close()
            await tf._stop(app)

    asyncio.run(scenario())


@pytest.mark.skipif(not (_has("ebooklib") and _has("openai") and _has("tiktoken")), reason="backend packages missing")
def test_chat_epub_migrate_library_flow(app_env, tmp_path, monkeypatch):
    import shutil

    import flows
    from glossarion_mobile.diagnostics.fake_llm_server import FAKE_MODEL, FakeLLMServer

    epub_src = APP_DIR / "assets" / "selftest" / "selftest_ko_12ch.epub"
    if not epub_src.is_file():
        pytest.skip("app/assets/selftest is generated by tools/prepare_assets.py")
    monkeypatch.setenv("GLOSSARION_HTTP_LOG", "0")
    tf = _foundations()
    picks = tmp_path / "picks"
    picks.mkdir()
    epub = picks / flows.EPUB_NAME
    shutil.copyfile(epub_src, epub)

    async def scenario(server):
        config = flows.write_ui_config(picks / flows.CONFIG_NAME, server.url, FAKE_MODEL)
        app, tester, driver = await _host_driver(tf, {flows.CONFIG_NAME: config, flows.EPUB_NAME: epub})
        try:
            await flows.wait_home(driver)
            await flows.import_desktop_config(driver)
            assert app.config_store.get("openai_base_url") == server.url
            await flows.chat_translate_and_migrate(driver, timeout=300)
            await flows.library_book_chapters(driver)
            if os.environ.get("GLOSSARION_UI_DUMP"):
                for row in tester.dump(600):
                    print(row)
        except Exception:
            for row in tester.dump(600):
                print(row)
            raise
        finally:
            app.jobs.close()
            await tf._stop(app)

    with FakeLLMServer() as server:
        asyncio.run(scenario(server))
        assert any(r.kind == "translate" for r in server.requests) or server.requests


def _ui_xml(*nodes) -> str:
    rows = "".join(
        f'<node text="{text}" content-desc="{desc}" package="{pkg}" bounds="[{x},{y}][{x + 100},{y + 50}]" />'
        for text, desc, pkg, x, y in nodes)
    return f'<?xml version="1.0"?><hierarchy rotation="0"><node package="{nodes[0][2] if nodes else ""}">{rows}</node></hierarchy>'


def test_documents_picker_finds_the_file_through_the_roots():
    """The DocumentsUI driver on canned uiautomator dumps: the app first (picker not up yet), then
    Recent without the file, the roots drawer with Downloads, then the Downloads listing."""
    import xml.etree.ElementTree as ET

    from android_device import DocumentsPicker

    docs = "com.google.android.documentsui"
    screens = [
        _ui_xml(("", "", "com.glossarion.app", 0, 0)),
        _ui_xml(("Recent", "", docs, 0, 0), ("", "Show roots", docs, 10, 10)),
        _ui_xml(("Downloads", "", docs, 200, 300), ("sdk_gphone64_x86_64", "", docs, 200, 400)),
        _ui_xml(("Downloads", "", docs, 0, 0), ("glossarion-ui-selftest.epub", "", docs, 300, 600)),
    ]

    class FakeAdb:
        def __init__(self):
            self.taps = []
            self.dumps = 0

        def dump_ui(self, label="dump"):
            self.dumps += 1
            return ET.fromstring(screens[min(self.dumps - 1, len(screens) - 1)])

        def tap_xy(self, x, y):
            self.taps.append((x, y))

    adb = FakeAdb()
    picker = DocumentsPicker(adb, timeout=60)

    async def no_sleep(_s):
        return None

    import android_device

    real_sleep = android_device.asyncio.sleep
    android_device.asyncio.sleep = no_sleep
    try:
        asyncio.run(picker.choose("glossarion-ui-selftest.epub"))
    finally:
        android_device.asyncio.sleep = real_sleep
    # Show roots, then Downloads in the drawer, then the file
    assert adb.taps == [(60, 35), (250, 325), (350, 625)]

    adb = FakeAdb()
    screens[:] = [_ui_xml(("Recent", "", docs, 0, 0))]
    picker = DocumentsPicker(adb, timeout=0.5)
    android_device.asyncio.sleep = no_sleep
    try:
        with pytest.raises(AssertionError, match="never listed"):
            asyncio.run(picker.choose("missing.epub"))
    finally:
        android_device.asyncio.sleep = real_sleep


def test_first_run_welcome_is_skipped(app_env):
    """A fresh install (the device tests' first launch): the Welcome flow, then Skip, then the home."""
    import flows

    tf = _foundations()

    async def scenario():
        app, tester, driver = await _host_driver(tf, {}, first_run=True)
        try:
            assert await flows.dismiss_welcome(driver, timeout=30) is True
            await flows.wait_home(driver, timeout=30)
        finally:
            app.jobs.close()
            await tf._stop(app)

    asyncio.run(scenario())
