"""Every inventory feature must be mapped to a mobile surface in docs/FEATURE_MAP.md.

docs/feature_inventory.toml is generated by tools/build_feature_inventory.py from the planning inventory.
FEATURE_MAP.md has one "## N. <group key> (...)" section per inventory group. Each section is a table whose rows are
"| index | feature name | mobile surface | notes |".

A feature passes when its group's section contains a row whose normalised name equals the inventory name, and
whose surface cell holds real text (not empty, not a bare dash, not "Hidden").
"""
from __future__ import annotations

import re
import unicodedata
from pathlib import Path

import pytest

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10
    tomllib = pytest.importorskip("tomli")

DOCS = Path(__file__).resolve().parents[1] / "docs"
INVENTORY = DOCS / "feature_inventory.toml"
FEATURE_MAP = DOCS / "FEATURE_MAP.md"

_CELL_SPLIT = re.compile(r"(?<!\\)\|")
_HEADING = re.compile(r"^##\s+\d+\.\s+([A-Za-z0-9_-]+)")
_EMPTY_SURFACES = {"", "-", "—", "–", "n/a", "hidden", "none", "tbd"}


def normalise(text: str) -> str:
    """Compare names ignoring Markdown escaping and emphasis, Unicode form, case and spacing."""
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\\|", "|").replace("`", "").replace("**", "")
    text = text.replace("’", "'").replace("‘", "'").replace("“", '"').replace("”", '"')
    return " ".join(text.split()).casefold()


def _cells(line: str) -> list[str]:
    parts = _CELL_SPLIT.split(line.strip())
    return [p.strip() for p in parts[1:-1]]


def parse_map(text: str) -> dict[str, list[dict]]:
    sections: dict[str, list[dict]] = {}
    current: list[dict] | None = None
    for line in text.splitlines():
        heading = _HEADING.match(line)
        if heading:
            current = sections.setdefault(heading.group(1), [])
            continue
        if line.startswith("## "):
            current = None
            continue
        if current is None or not line.startswith("|") or line.startswith("|---"):
            continue
        cells = _cells(line)
        if len(cells) < 3 or cells[0] in ("#", "Setting"):
            continue
        current.append({"index": cells[0], "name": cells[1], "surface": cells[2]})
    return sections


@pytest.fixture(scope="module")
def inventory() -> dict:
    assert INVENTORY.is_file(), f"missing {INVENTORY}; run tools/build_feature_inventory.py"
    return tomllib.loads(INVENTORY.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def feature_map() -> dict[str, list[dict]]:
    assert FEATURE_MAP.is_file(), f"missing {FEATURE_MAP}"
    return parse_map(FEATURE_MAP.read_text(encoding="utf-8"))


def test_inventory_is_consistent(inventory):
    groups = inventory["group"]
    assert groups, "inventory has no groups"
    keys = [g["key"] for g in groups]
    assert len(keys) == len(set(keys)), "duplicate group keys"
    total = 0
    for g in groups:
        feats = g.get("feature", [])
        assert g["count"] == len(feats), g["key"]
        assert [f["index"] for f in feats] == list(range(len(feats))), g["key"]
        for f in feats:
            assert f["name"].strip(), f"{g['key']} #{f['index']}: empty name"
            assert f["mobile"].strip(), f"{g['key']} #{f['index']}: empty classification"
        total += len(feats)
    assert total == inventory["total"]
    assert sum(inventory["classes"].values()) == total


def test_every_group_has_a_map_section(inventory, feature_map):
    missing = [g["key"] for g in inventory["group"] if g["key"] not in feature_map]
    assert not missing, f"FEATURE_MAP.md has no section for: {missing}"


def test_every_feature_is_mapped_with_a_surface(inventory, feature_map):
    problems = []
    for g in inventory["group"]:
        rows = feature_map.get(g["key"], [])
        by_name: dict[str, list[dict]] = {}
        for row in rows:
            by_name.setdefault(normalise(row["name"]), []).append(row)
        for f in g.get("feature", []):
            matches = by_name.get(normalise(f["name"]))
            label = f"{g['key']} #{f['index']} {f['name']!r}"
            if not matches:
                problems.append(f"{label}: no row in FEATURE_MAP.md")
                continue
            if not any(normalise(r["surface"]).strip(" .") not in _EMPTY_SURFACES for r in matches):
                problems.append(f"{label}: empty surface")
    assert not problems, f"{len(problems)} unmapped feature(s):\n" + "\n".join(problems[:50])


def test_map_has_no_rows_outside_the_inventory(inventory, feature_map):
    """Inventory sections must not carry stale rows (renamed or removed features)."""
    stale = []
    for g in inventory["group"]:
        names = {normalise(f["name"]) for f in g.get("feature", [])}
        for row in feature_map.get(g["key"], []):
            if normalise(row["name"]) not in names:
                stale.append(f"{g['key']} row {row['index']}: {row['name']!r}")
    assert not stale, "rows not in the inventory:\n" + "\n".join(stale[:50])
