"""Acceptance for the owner's device report #8 (2026-10-08): "I should be able to just directly [use]
my epub library from direct chat, not manually do clicks".

The real app on a fake Flet session (the ``test_ui_flows`` pattern: ``host_tester.PyTester`` +
``ui_driver.UiDriver`` dispatch the events Flutter would send), the fake OpenAI server and
Settings › Import from desktop; the Library is filled through the Library's own "Import EPUB"
button (three EPUBs with covers, copied into Library/Raw with their workspaces scaffolded):

* ＋ › From Library (a first-row tile of the ＋ sheet) opens the Library picker INSIDE the chat (the
  route and the chat stay; no trip to the Library screen): one searchable list of the Library's
  own book rows with covers and progress pills, newest first (Date order, not import / A-Z order);
* one tap on a book attaches it (the composer's FileChip) and the picker closes;
* Send defaults to "Save to: Library": Start runs ONE ``translate`` job over the book's Library/Raw
  file in the book's own Library workspace (the folder Import made), tied to the chat and the book;
  the chat's Library-job card opens the Book page, which shows the running job and, once done, the
  translated chapters; nothing is written under the chat's Direct Text folder; attaching the same
  book again later continues that workspace (nothing re-translated, no second copy);
* ``/library <partial title>`` (case-insensitive, the Library search) attaches the one match;
  several matches open the picker prefilled; none says so; ``/library`` alone, the slash-popover
  tap and the empty-chat "From Library" chip open the in-chat picker;
* right after launch (Library never opened, no model set up so Send is blocked) ``/library <title>``
  and ＋ › From Library still attach: the Library is scanned on first use and a command that sends
  nothing to a model runs from Send / Enter too;
* several books picked at once make one batch (BatchPlanCard -> one ``translate`` job, each book
  into its own Library workspace): a long-press starts the picker's multi-selection, like the
  Library's own shelves.

Real data stays out: ``app_env`` bootstraps the app into tmp storage (HOME, OUTPUT_DIRECTORY,
GLOSSARION_LIBRARY_DIR, the config), USERPROFILE / APPDATA point at tmp and GLOSSARION_HTTP_LOG=0.

Run from src/mobile with the mobile venv:
    python -m pytest -p no:cacheprovider -W ignore -o console_output_style=classic tests_host/test_devfix_issue8.py
"""

from __future__ import annotations

import asyncio
import importlib.util
import json
import os
import sys
import time
from pathlib import Path

import pytest

MOBILE_DIR = Path(__file__).resolve().parents[1]
APP_DIR = MOBILE_DIR / "app"
TESTS_DIR = MOBILE_DIR / "tests"
for _path in (APP_DIR, TESTS_DIR):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))


def _has(module: str) -> bool:
    try:
        return importlib.util.find_spec(module) is not None
    except (ImportError, ValueError):
        return False


def _tiktoken_assets() -> bool:
    folder = APP_DIR / "assets" / "tiktoken"
    return folder.is_dir() and any(p.is_file() and not p.suffix for p in folder.iterdir())


pytestmark = [
    pytest.mark.skipif(not (_has("flet") and _has("msgpack")), reason="flet/msgpack not installed"),
    pytest.mark.skipif(not (_has("ebooklib") and _has("openai") and _has("tiktoken") and _has("bs4")),
                       reason="backend packages missing"),
    # offline: the pipeline counts tokens with the encodings tools/prepare_assets.py ships
    pytest.mark.skipif(not _tiktoken_assets(), reason="app/assets/tiktoken is generated by tools/prepare_assets.py"),
]

_TB_SPEC = importlib.util.spec_from_file_location("_glossarion_tb_helpers_devfix8",
                                                  Path(__file__).with_name("test_bootstrap.py"))
_TB = importlib.util.module_from_spec(_TB_SPEC)
_TB_SPEC.loader.exec_module(_TB)
storage = _TB.storage
app_env = _TB.app_env

ATTACH = "Attach, output mode and tools"
COMPOSER_HINT = "Message to translate…"
#: the Library books: (file stem, chapters, cover colour), imported in this order
BOOKS = (("Alpha Saga", 2, (200, 40, 40)), ("Beta Chronicle", 2, (40, 160, 60)), ("Gamma Tales", 2, (40, 60, 200)))
#: workspace ages (s) after the import: Beta newest, Gamma, Alpha oldest (neither import nor A-Z order)
AGES = {"Beta Chronicle": 0, "Gamma Tales": 3600, "Alpha Saga": 7200}
NEWEST_FIRST = ("Beta Chronicle", "Gamma Tales", "Alpha Saga")


def _foundations():
    spec = importlib.util.spec_from_file_location("_glossarion_tf_helpers_devfix8",
                                                  Path(__file__).with_name("test_ui_foundations.py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _norm(path) -> str:
    return os.path.normcase(os.path.abspath(str(path)))


def _key(control):
    key = getattr(control, "key", None)
    return getattr(key, "value", key)


def _epub(path: Path, title: str, chapters: int, rgb: tuple) -> Path:
    """A small Korean EPUB with its own identifier and a PNG cover (the picker shows covers)."""
    from ebooklib import epub

    from glossarion_mobile.diagnostics.fake_llm_server import png_bytes

    book = epub.EpubBook()
    book.set_identifier(f"glossarion-devfix8-{title.lower().replace(' ', '-')}")
    book.set_title(title)
    book.set_language("ko")
    book.add_author("Glossarion")
    book.set_cover("cover.png", png_bytes(60, 90, rgb))
    items = []
    for index in range(1, chapters + 1):
        chapter = epub.EpubHtml(title=f"제{index}장", file_name=f"chapter{index:04d}.xhtml", lang="ko")
        chapter.content = (f"<html><head><title>제{index}장</title></head><body><h1>제{index}장</h1>"
                           f"<p>{title} 이야기의 {index}번째 장입니다. 주인공은 길을 떠났다.</p></body></html>")
        book.add_item(chapter)
        items.append(chapter)
    book.toc = tuple(items)
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())
    book.spine = ["nav", *items]
    path.parent.mkdir(parents=True, exist_ok=True)
    epub.write_epub(str(path), book)
    return path


@pytest.fixture
def isolated(app_env, tmp_path, monkeypatch):
    """``app_env`` (tmp FLET_APP_STORAGE_*, bootstrap: HOME / OUTPUT_DIRECTORY / Library / config in
    tmp) plus USERPROFILE / APPDATA in tmp and no HTTP log; the picks: config + three EPUBs."""
    monkeypatch.setenv("GLOSSARION_HTTP_LOG", "0")
    monkeypatch.setenv("USERPROFILE", str(tmp_path / "home"))
    monkeypatch.setenv("APPDATA", str(tmp_path / "appdata"))
    monkeypatch.setenv("LOCALAPPDATA", str(tmp_path / "appdata"))
    picks = tmp_path / "picks"
    files = {f"{stem}.epub": _epub(picks / f"{stem}.epub", stem, chapters, rgb) for stem, chapters, rgb in BOOKS}
    return picks, files


async def _host_driver(tf, files: dict):
    from host_tester import HostPicker, PyTester
    from ui_driver import UiDriver

    _m, conn, session, page, app = await tf._start("android")
    picker = HostPicker(files)
    bridge = getattr(app, "files", None)
    if bridge is not None:
        bridge._get_picker = lambda: picker  # what the app's FilePicker service would answer

    async def back():
        views = list(page.views or [])
        if len(views) > 1:
            await session.dispatch_event(page._i, "view_pop", {"route": views[-1].route})

    tester = PyTester(session, page)
    driver = UiDriver(tester, picker=picker, back=back, poll_ms=100, log=lambda *_a: None)
    return app, page, tester, driver


async def _until(predicate, timeout: float = 30.0, interval: float = 0.1):
    deadline = time.monotonic() + timeout
    while True:
        value = predicate()
        if value:
            return value
        if time.monotonic() >= deadline:
            return value
        await asyncio.sleep(interval)


def _route(page) -> str:
    views = list(page.views or [])
    return str(views[-1].route) if views else ""


def _rows(service) -> dict:
    return {str(b.get("folder_name") or b.get("name")): dict(b) for b in service.snapshot.all_books()}


async def _start_with_library(tf, server, picks: Path, files: dict):
    """The app with the fake model imported from a desktop config and the three books imported
    through Library › Import EPUB; workspace mtimes set to ``AGES``. Returns (app, page, tester,
    driver, {stem: {bid, raw, workspace}})."""
    import flows
    from glossarion_mobile.diagnostics.fake_llm_server import FAKE_MODEL

    files = dict(files)
    files[flows.CONFIG_NAME] = flows.write_ui_config(picks / flows.CONFIG_NAME, server.url, FAKE_MODEL)
    app, page, tester, driver = await _host_driver(tf, files)
    await flows.wait_home(driver)
    await flows.import_desktop_config(driver)
    await flows.open_drawer(driver)
    await driver.tap(key="dest-library")
    await driver.wait(key="lib-search", timeout=60)
    for stem, _chapters, _rgb in BOOKS:
        name = f"{stem}.epub"
        await driver.pick_file(name, lambda: driver.tap(key="lib-fab"))  # the In progress shelf's Import EPUB
        await driver.wait(contains=f"Added to Library: {name}", timeout=60)
    service = app.library
    assert await _until(lambda: len(service.snapshot.all_books()) >= 3, 60), _rows(service).keys()
    rows = _rows(service)
    assert set(rows) == {stem for stem, _c, _r in BOOKS}, rows.keys()
    now = time.time()
    for stem, age in AGES.items():
        folder = rows[stem].get("output_folder") or ""
        assert folder and os.path.isdir(folder), rows[stem]  # Import scaffolded the book's workspace
        os.utime(folder, (now - age, now - age))
    service.mark_dirty()
    await service.refresh(reason="devfix8: workspace ages")
    books = {}
    for stem, row in _rows(service).items():
        raw = row.get("raw_source_path") or ""
        assert raw and os.path.isfile(raw) and Path(raw).parent.name == "Raw", row  # copied into Library/Raw
        books[stem] = {"bid": service.bid_for(row), "raw": raw, "workspace": row["output_folder"]}
    await flows.go_home(driver)
    return app, page, tester, driver, books


async def _new_chat(app, page, driver) -> str:
    await driver.tap(tooltip="New chat")
    await driver.wait(key="transcript-empty", timeout=30)
    return app.chat_view.cid


def _newest_first(service, books: dict, stems) -> list:
    """``book-<bid>`` keys of ``stems`` by the Library scan's current mtime, newest first (a run
    touches its workspace, so a book translated in this test moves to the top)."""
    rows = _rows(service)
    ordered = sorted(stems, key=lambda stem: float(rows[stem].get("mtime") or 0.0), reverse=True)
    return [f"book-{books[stem]['bid']}" for stem in ordered]


def _picker_order(picker) -> list:
    """The picker list's book rows top to bottom as ``book-<bid>`` keys."""
    keys = []
    for control in picker.list_view.controls:
        key = _key(control)
        if isinstance(key, str) and key.startswith("pick-") and getattr(control, "controls", None):
            key = _key(control.controls[0])  # an ineligible row: the muted row + its ReasonChip
        keys.append(key)
    return keys


async def _open_picker(app, driver):
    """The chat's Library picker that the last action opened (every earlier one was closed)."""
    view = app.chat_view

    def opened():
        picker = view.library_picker
        return picker if picker is not None and picker.sheet.open else None

    picker = await _until(opened, 15)
    assert picker is not None, "no in-chat Library picker opened"
    assert await _until(lambda: picker.loaded, 30), "the picker never loaded its rows"
    await driver.wait(key="picker-title", timeout=10)
    return picker


async def _send_text(driver, text: str) -> None:
    await driver.enter(text, text=COMPOSER_HINT)
    await driver.tap(key="send-idle_ready", timeout=10)


def test_owner_issue8_library_book_attached_and_translated_from_the_chat(isolated):
    from glossarion_mobile.diagnostics.fake_llm_server import FakeLLMServer
    from glossarion_mobile.ui.chat.chat_view import LIBRARY_ATTACHMENT_META
    from glossarion_mobile.ui.sheets.plus_sheet import ATTACH_TILES

    picks, files = isolated
    tf = _foundations()

    async def scenario(server):
        import flows

        app, page, tester, driver, books = await _start_with_library(tf, server, picks, files)
        try:
            view = app.chat_view
            chats = app.chat_feature.chats
            js = app.job_service
            cid = await _new_chat(app, page, driver)
            chat_route = _route(page)
            chat_screen = app.shell.top_screen
            # ---- ＋ › From Library: a first-row tile, opens the picker in the chat ------------------
            assert [t[0] for t in ATTACH_TILES].index("library") <= 1, ATTACH_TILES  # one tap, no scrolling
            await driver.tap(tooltip=ATTACH)
            await driver.wait(key="attach-library", timeout=10)
            assert view.plus_sheet.tiles["library"].on_click is not None  # enabled (no ReasonChip)
            await driver.tap(key="attach-library")
            picker = await _open_picker(app, driver)
            assert _route(page) == chat_route and app.shell.top_screen is chat_screen  # still the chat
            assert not view.plus_sheet.dialog.open  # the ＋ sheet closed, the picker took its place
            assert picker.sheet.open and picker.title == "Attach from Library"
            assert picker.segments == ("library",) and picker.segment_row.visible is False  # one list
            await driver.wait(key="picker-search", timeout=5)  # the Library's "Filter title or tag…" field
            assert picker.search_field.hint_text == "Filter title or tag…"
            # newest first (Date: Beta, Gamma, Alpha), the Library's own rows: pill, no ⋯, covers
            order = [f"book-{books[stem]['bid']}" for stem in NEWEST_FIRST]
            assert _picker_order(picker) == order
            assert picker.status.value == "3 items"
            for stem in NEWEST_FIRST:
                row = await driver.wait(key=f"book-{books[stem]['bid']}", timeout=5)
                assert row.count == 1
            for key, (row, _control) in picker.book_cards.items():
                assert row.show_more is False and row.model.pill_text  # "🆕 Not started"
            covers = await _until(lambda: all(r.cover_src and os.path.isfile(r.cover_src)
                                              for r, _c in picker.book_cards.values()), 30)
            assert covers, {k: r.cover_src for k, (r, _c) in picker.book_cards.items()}  # each EPUB's own cover
            assert len({r.cover_src for r, _c in picker.book_cards.values()}) == 3
            # search: the Library's title / tag filter, on every change
            await driver.enter("gAmMa", key="picker-search")
            assert _picker_order(picker) == [f"book-{books['Gamma Tales']['bid']}"]
            assert picker.status.value == "1 of 3 items"
            await driver.tap(tooltip="Clear search")
            assert _picker_order(picker) == order
            # ---- one tap attaches the book: FileChip, the picker closes, the chat stays -----------------
            gamma = books["Gamma Tales"]
            await driver.tap(key=f"book-{gamma['bid']}")
            assert await _until(lambda: not picker.sheet.open, 5), "the picker did not close"
            assert _route(page) == chat_route and app.shell.top_screen is chat_screen
            attached = view.composer.attachment or {}
            assert _norm(attached.get("path")) == _norm(gamma["raw"]) and attached.get("name") == "Gamma Tales.epub"
            await driver.wait(text="Gamma Tales.epub", timeout=5)  # the composer FileChip
            await driver.wait(tooltip="Remove attachment", timeout=5)
            await driver.wait(text="Attached Gamma Tales.epub from the Library", timeout=5)
            meta = chats.meta(cid).get(LIBRARY_ATTACHMENT_META)
            assert meta == {"bid": gamma["bid"], "path": gamma["raw"]}
            assert js.snapshot() is None and not js.view().queue  # attaching never starts anything
            # ---- Send: the Plan card defaults to "Save to: Library" (the book's own workspace) ----------
            await driver.tap(key="send-idle_ready", timeout=10)
            await driver.wait(text="Ready to translate", timeout=30)
            await driver.wait(text="Save to: Library", timeout=10)
            await driver.wait(contains="📚 Library · ", timeout=10)
            plan = chats.meta(cid).get("pending_plan") or {}
            assert plan.get("destination") == "library" and plan.get("library_bid") == gamma["bid"]
            server.hold()  # park the model: the job stays running while the Book page is checked
            await driver.tap(text="Start")
            if await driver.exists(text="Keep translations running", timeout=5):
                await driver.tap(text="Not now")
            snap = await _until(lambda: js.snapshot(), 60)
            assert snap is not None, "Start did not run a job"
            job_id = snap.id
            assert str(getattr(snap.spec.kind, "value", snap.spec.kind)) == "translate"
            assert tuple(_norm(p) for p in snap.spec.inputs) == (_norm(gamma["raw"]),)  # the Library/Raw file
            assert snap.spec.origin.get("cid") == cid and snap.spec.origin.get("bid") == gamma["bid"]
            assert "chat_id" not in snap.spec.params  # not a Direct Text (chat Attachments) run
            assert await _until(lambda: (js.snapshot(job_id).output_dir or ""), 60)
            assert _norm(js.snapshot(job_id).output_dir) == _norm(gamma["workspace"])  # the book's own workspace
            assert len(js.view().queue) == 0
            # ---- the chat's Library-job card opens the Book page, which shows the running job ----------
            await driver.wait(key="libjob-library", timeout=30)
            await driver.tap(key="libjob-library")
            book_page = await _until(lambda: app.shell.top_screen if type(app.shell.top_screen).__name__ ==
                                     "BookPageScreen" else None, 30)
            assert book_page is not None and book_page.bid == gamma["bid"], _route(page)
            assert await _until(lambda: book_page.job is not None and book_page.job.id == job_id, 30)
            await driver.wait(key="strip-job", timeout=10)
            assert book_page.strip_job.visible and book_page.strip_job_text.value.startswith("⏳ ")
            # ---- done: the chapters are translated in the book's workspace, never in the chat's ---------
            server.release()
            done = await _until(lambda: (s := js.snapshot(job_id)) is not None
                                and str(getattr(s.state, "value", s.state)) in ("DONE", "FAILED", "STOPPED",
                                                                                 "CANCELLED", "INTERRUPTED")
                                and s, 240)
            assert done and str(getattr(done.state, "value", done.state)) == "DONE", getattr(done, "error", done)
            assert server.count("translation") >= 2  # both chapters went through the (fake) model
            assert await _until(lambda: book_page.job is None, 30)
            # the Book page reloads the book's progress (its own workspace): both chapters completed
            def chapters_done():
                rows_ = {str(r.key).rsplit(":", 1)[-1]: r.status for r in getattr(book_page.progress, "rows", ())
                         if r.kind == "chapter"}
                return all(rows_.get(f"chapter{n:04d}.xhtml") == "completed" for n in (1, 2))

            assert await _until(chapters_done, 60), "\n".join(
                f"{r.key} {r.kind} {r.status}" for r in getattr(book_page.progress, "rows", ()))
            assert _norm(book_page.progress.output_dir) == _norm(gamma["workspace"])
            assert not [r for r in book_page.progress.rows if r.status == "failed"]
            await driver.tap(text="Chapters", timeout=30)
            await driver.wait(key="ch-stats", timeout=60)
            await driver.wait(contains="Not Translated 0", timeout=60)
            await driver.wait(contains="Failed 0", timeout=30)
            progress = json.loads((Path(gamma["workspace"]) / "translation_progress.json").read_text(encoding="utf-8"))
            assert progress.get("chapters"), progress  # the shared pipeline wrote the book's own progress
            # no Direct Text run: nothing translated under the chat's folder (no Attachments/<stem> workspace)
            direct_text = Path(os.environ["OUTPUT_DIRECTORY"]) / "Direct Text"
            strays = [str(p) for p in direct_text.rglob("translation_progress.json")] if direct_text.is_dir() else []
            strays += [str(p) for p in direct_text.rglob("Attachments")] if direct_text.is_dir() else []
            assert strays == []
            await app.library.refresh(reason="devfix8: after the run")
            after = _rows(app.library)
            assert _norm(after["Gamma Tales"]["output_folder"]) == _norm(gamma["workspace"])
            assert app.library.bid_for(after["Gamma Tales"]) == gamma["bid"]
            await flows.go_home(driver)

            # ---- /library <partial title>: the one match is attached at once (case-insensitive) --------
            alpha = books["Alpha Saga"]
            cid2 = await _new_chat(app, page, driver)
            route2 = _route(page)
            opened = view.library_picker
            await _send_text(driver, "/library ALP")
            await driver.wait(text="Alpha Saga.epub", timeout=30)
            assert _norm((view.composer.attachment or {}).get("path")) == _norm(alpha["raw"])
            assert chats.meta(cid2).get(LIBRARY_ATTACHMENT_META) == {"bid": alpha["bid"], "path": alpha["raw"]}
            assert view.library_picker is opened and _route(page) == route2  # no picker, no navigation
            assert view.composer.text == ""  # the command ran instead of being sent
            # several matches ("ta": Beta, Gamma) open the picker prefilled, newest first
            await _new_chat(app, page, driver)
            await _send_text(driver, "/library ta")
            picker = await _open_picker(app, driver)
            assert picker.query == "ta" and picker.search_field.value == "ta"
            # (Gamma's run touched its workspace: it is the newest book now)
            assert _picker_order(picker) == _newest_first(app.library, books, ("Beta Chronicle", "Gamma Tales"))
            assert _picker_order(picker)[0] == f"book-{books['Gamma Tales']['bid']}"
            models = {row.model.bid: row.model for row, _c in picker.book_cards.values()}
            assert "Not started" in str(models[books["Beta Chronicle"]["bid"]].pill_text)
            # the translated (and compiled) book: the Library's Completed card, same book id
            assert models[books["Gamma Tales"]["bid"]].state == "completed", models[books["Gamma Tales"]["bid"]]
            await driver.tap(key="picker-cancel")
            assert await _until(lambda: not picker.sheet.open, 5)
            # no match: says so (with Open Library), nothing attached, no navigation
            route_ta = _route(page)
            await _send_text(driver, "/library zzz")
            await driver.wait(contains="No Library book matches", timeout=10)
            assert view.composer.attachment is None and _route(page) == route_ta
            # ---- /library alone, the popover tap and the empty-chat chip open the in-chat picker ------
            await _send_text(driver, "/library")
            picker = await _open_picker(app, driver)
            assert picker.query == "" and _picker_order(picker) == _newest_first(app.library, books, NEWEST_FIRST)
            await driver.tap(key="picker-cancel")
            assert await _until(lambda: not picker.sheet.open, 5)
            await driver.enter("/lib", text=COMPOSER_HINT)
            popover_items = [c for c in tester._walk() if str(_key(c) or "").startswith("slash-library-")]
            assert popover_items, "the slash popover offers no /library"
            await tester.tap(await tester.find_by_key(_key(popover_items[0])))
            picker = await _open_picker(app, driver)
            await driver.tap(key="picker-cancel")
            assert await _until(lambda: not picker.sheet.open, 5)
            route3 = _route(page)
            await driver.enter("", text=COMPOSER_HINT)
            await driver.wait(key="suggest-From Library", timeout=10)
            await driver.tap(key="suggest-From Library")
            picker = await _open_picker(app, driver)
            assert _route(page) == route3
            await driver.tap(key=f"book-{books['Beta Chronicle']['bid']}")
            await driver.wait(text="Beta Chronicle.epub", timeout=10)
            assert _norm((view.composer.attachment or {}).get("path")) == _norm(books["Beta Chronicle"]["raw"])

            # ---- the same book again from a chat continues its workspace (nothing re-translated) -------
            cid4 = await _new_chat(app, page, driver)
            before_dirs = sorted(p.name for p in Path(os.environ["OUTPUT_DIRECTORY"]).iterdir() if p.is_dir())
            await _send_text(driver, "/library gamma tales")
            await driver.wait(text="Gamma Tales.epub", timeout=30)
            assert chats.meta(cid4).get(LIBRARY_ATTACHMENT_META) == {"bid": gamma["bid"], "path": gamma["raw"]}
            await driver.tap(key="send-idle_ready", timeout=10)
            await driver.wait(text="Save to: Library", timeout=30)
            line = await _until(lambda: next((c for c in tester._walk() if _key(c) == "plan-library"
                                              and "Not started" not in str(c.value or "")
                                              and str(c.value or "").startswith("📚 Library · ")), None), 15)
            assert line is not None  # the Plan card shows the book's Library progress
            mark = server.mark()
            await driver.tap(text="Start")
            second = await _until(lambda: next((s for s in js.view().history
                                                if s.id != job_id and s.spec.origin.get("cid") == cid4), None), 120)
            assert second is not None and str(getattr(second.state, "value", second.state)) == "DONE", second
            assert tuple(_norm(p) for p in second.spec.inputs) == (_norm(gamma["raw"]),)
            assert _norm(second.output_dir) == _norm(gamma["workspace"])  # the same workspace, resumed
            assert server.count("translation", since=mark) == 0  # its chapters were already done
            after_dirs = sorted(p.name for p in Path(os.environ["OUTPUT_DIRECTORY"]).iterdir() if p.is_dir())
            assert after_dirs == before_dirs  # no "Gamma Tales (2)" copy
        except Exception:
            for row in tester.dump(400):
                print(row)
            raise
        finally:
            server.release()
            app.jobs.close()
            await tf._stop(app)

    with FakeLLMServer() as server:
        asyncio.run(scenario(server))


def test_owner_issue8_first_use_after_launch_needs_no_library_visit(isolated):
    """A user with a Library on disk opens the app and, without ever visiting the Library screen,
    attaches books from the chat: ``/library alp`` (the Library is scanned quietly on first use) and
    ＋ › From Library. No model is set up here (the default ChatGPT route is not signed in, so Send is
    *blocked*): attaching a book sends nothing to a model, so ``/library <title>`` must still run -
    from the slash popover AND from Send / Enter (a blocked Send explains the block only for text it
    would really send)."""
    import library_core

    from glossarion_mobile.ui.chat.chat_view import LIBRARY_ATTACHMENT_META

    picks, files = isolated
    imported = library_core.import_paths([str(files[f"{stem}.epub"]) for stem, _c, _r in BOOKS], "raw", None,
                                         copy_into_library=True)
    assert len(imported["imported"]) == 3 and not imported["errors"], imported
    output_root = Path(os.environ["OUTPUT_DIRECTORY"])
    now = time.time()
    for stem, age in AGES.items():
        folder = output_root / stem
        assert folder.is_dir(), sorted(p.name for p in output_root.iterdir())
        os.utime(folder, (now - age, now - age))
    tf = _foundations()

    async def scenario():
        import flows

        app, page, tester, driver = await _host_driver(tf, {})
        try:
            await flows.wait_home(driver)
            view = app.chat_view
            chats = app.chat_feature.chats
            route = _route(page)
            await driver.wait(key="send-blocked", timeout=30)  # not signed in: Send explains the block
            await driver.enter("/library alp", text=COMPOSER_HINT)
            items = [c for c in tester._walk() if str(_key(c) or "").startswith("slash-library-")]
            assert items, "the slash popover offers no /library"
            await tester.tap(await tester.find_by_key(_key(items[0])))  # the popover row runs it with "alp"
            await driver.wait(text="Alpha Saga.epub", timeout=60)
            rows = _rows(app.library)
            alpha = rows["Alpha Saga"]
            assert chats.meta(view.cid).get(LIBRARY_ATTACHMENT_META) == {
                "bid": app.library.bid_for(alpha), "path": alpha["raw_source_path"]}
            assert _route(page) == route
            await driver.tap(tooltip="Remove attachment")
            assert view.composer.attachment is None
            assert LIBRARY_ATTACHMENT_META not in chats.meta(view.cid)  # removing it forgets the book
            await driver.tap(tooltip=ATTACH)
            await driver.tap(key="attach-library", timeout=10)
            picker = await _open_picker(app, driver)
            books = {stem: {"bid": app.library.bid_for(row)} for stem, row in rows.items()}
            assert _picker_order(picker) == [f"book-{books[stem]['bid']}" for stem in NEWEST_FIRST]
            assert _route(page) == route
            await driver.tap(key="picker-cancel")
            assert await _until(lambda: not picker.sheet.open, 5)
            # Send / Enter on a complete /library command runs it even while Send is blocked
            await driver.enter("/library gam", text=COMPOSER_HINT)
            await driver.tap(key="send-blocked", timeout=10)
            await driver.pump(300)
            attached = view.composer.attachment or {}
            assert attached.get("name") == "Gamma Tales.epub", (
                "Send on '/library gam' explained the blocked model instead of running the command "
                f"(composer text {view.composer.text!r}, attachment {attached!r})")
        except Exception:
            for row in tester.dump(200):
                print(row)
            raise
        finally:
            app.jobs.close()
            await tf._stop(app)

    asyncio.run(scenario())


def test_owner_issue8_several_library_books_make_one_batch(isolated):
    """Multi-select in the in-chat Library picker: a long-press starts a selection (like the Library's
    own shelves), more taps add books, "Use N" puts them in one BatchPlanCard; its Start runs one
    ``translate`` job over their Library/Raw files (each book's own workspace, the desktop multi-file
    run). A plain tap still attaches one book at once (one tap, test above)."""
    from glossarion_mobile.diagnostics.fake_llm_server import FakeLLMServer

    picks, files = isolated
    tf = _foundations()

    async def scenario(server):
        app, page, tester, driver, books = await _start_with_library(tf, server, picks, files)
        try:
            view = app.chat_view
            chats = app.chat_feature.chats
            js = app.job_service
            cid = await _new_chat(app, page, driver)
            await driver.tap(tooltip=ATTACH)
            await driver.tap(key="attach-library", timeout=10)
            picker = await _open_picker(app, driver)
            beta, gamma = books["Beta Chronicle"], books["Gamma Tales"]
            await tester.long_press(await driver.wait(key=f"book-{beta['bid']}", timeout=10))
            await driver.pump(200)
            assert picker.sheet.open, "a long-press closed the picker"
            assert picker.multi and set(picker.selected) == {t.key for t in picker.rows["library"]
                                                             if t.bid == beta["bid"]}, (
                "a long-press on a Library row does not start a multi-selection in the chat picker")
            await driver.tap(key=f"book-{gamma['bid']}")
            assert len(picker.selected) == 2 and picker.sheet.open
            await driver.wait(text="Use 2", timeout=5)
            await driver.tap(key="picker-done")
            assert await _until(lambda: not picker.sheet.open, 5)
            batch = chats.meta(cid).get("pending_batch") or {}
            assert sorted(_norm(p) for p in batch.get("files") or ()) == sorted(
                _norm(b["raw"]) for b in (beta, gamma)), batch
            await driver.wait(key="batch-start", timeout=30)
            await driver.tap(key="batch-start")
            if await driver.exists(text="Keep translations running", timeout=5):
                await driver.tap(text="Not now")
            snap = await _until(lambda: js.snapshot() or (js.view().history[0] if js.view().history else None), 60)
            assert snap is not None
            assert str(getattr(snap.spec.kind, "value", snap.spec.kind)) == "translate"
            assert sorted(_norm(p) for p in snap.spec.inputs) == sorted(_norm(b["raw"]) for b in (beta, gamma))
            assert snap.spec.origin.get("cid") == cid
            done = await _until(lambda: (s := js.snapshot(snap.id)) is not None and str(
                getattr(s.state, "value", s.state)) in ("DONE", "FAILED", "STOPPED", "CANCELLED") and s, 240)
            assert done and str(getattr(done.state, "value", done.state)) == "DONE", done
            # each book went into its own Library workspace (the desktop multi-file run)
            assert sorted(_norm(d) for d in (done.output_dirs or {}).values()) == sorted(
                _norm(b["workspace"]) for b in (beta, gamma)), done.output_dirs
        except Exception:
            for row in tester.dump(200):
                print(row)
            raise
        finally:
            app.jobs.close()
            await tf._stop(app)

    with FakeLLMServer() as server:
        asyncio.run(scenario(server))
