"""Generate docs/feature_inventory.toml from the planning feature-inventory JSON.

Usage:
    python tools/build_feature_inventory.py <inventory.json> [--out docs/feature_inventory.toml]

The JSON is the planning workflow result: either the raw result object or a wrapper with a "result" key. It holds:
- ``readers[]``, each with ``key``, ``area`` and ``features[]`` (``name`` and ``mobile`` classification);
- ``critic.missing_features[]``, features the critic found missing from the readers.

The TOML keeps one ``[[group]]`` per reader key, in source order, plus a final ``critic-missing`` group. Every
feature records its index, exact name and mobile classification. Critic features have no classification, so they
get ``mobile = "critic-gap"``.

``tests_host/test_feature_map.py`` checks that every feature listed here has a row with a non-empty surface in
``docs/FEATURE_MAP.md``. Stdlib only; runs on Python 3.10+.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

MOBILE_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = MOBILE_ROOT / "docs" / "feature_inventory.toml"
CRITIC_KEY = "critic-missing"
CRITIC_CLASS = "critic-gap"


def toml_str(value: str) -> str:
    """Return a TOML basic string.

    JSON string escapes (\\" \\\\ \\n \\t \\uXXXX) are a subset of TOML basic-string escapes, so json.dumps is valid TOML.
    """
    return json.dumps(str(value), ensure_ascii=False)


def load_result(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    result = data.get("result", data) if isinstance(data, dict) else None
    if not isinstance(result, dict) or "readers" not in result:
        raise SystemExit(f"{path}: no 'readers' found (expected the inventory result object)")
    return result


def build_groups(result: dict) -> list[dict]:
    groups: list[dict] = []
    seen: set[str] = set()
    for reader in result["readers"]:
        key = str(reader["key"]).strip()
        if not key or key in seen:
            raise SystemExit(f"bad or duplicate reader key: {key!r}")
        seen.add(key)
        features = []
        for i, feat in enumerate(reader.get("features") or []):
            name = str(feat.get("name", "")).strip()
            if not name:
                raise SystemExit(f"{key} #{i}: feature without a name")
            features.append({"index": i, "name": name, "mobile": str(feat.get("mobile") or "unclassified")})
        groups.append({"key": key, "area": str(reader.get("area") or key), "source": "reader", "features": features})
    critic = (result.get("critic") or {}).get("missing_features") or []
    groups.append({
        "key": CRITIC_KEY,
        "area": "Features the critic found missing from the reader inventories",
        "source": "critic",
        "features": [
            {"index": i, "name": str(f.get("name", "")).strip(), "mobile": CRITIC_CLASS}
            for i, f in enumerate(critic)
        ],
    })
    return groups


def render(groups: list[dict], source_name: str, source_sha: str) -> str:
    total = sum(len(g["features"]) for g in groups)
    classes: dict[str, int] = {}
    for g in groups:
        for f in g["features"]:
            classes[f["mobile"]] = classes.get(f["mobile"], 0) + 1
    lines = [
        "# Glossarion mobile feature inventory.",
        "# GENERATED by src/mobile/tools/build_feature_inventory.py; do not edit by hand.",
        f"# Source: {source_name} (sha256 {source_sha[:16]}). Regenerate with:",
        "#   python tools/build_feature_inventory.py <inventory.json>",
        "# Every feature must appear in docs/FEATURE_MAP.md (checked by tests_host/test_feature_map.py).",
        "",
        "schema = 1",
        f"total = {total}",
        "",
        "[classes]",
    ]
    for name in sorted(classes):
        lines.append(f"{toml_str(name)} = {classes[name]}")
    for g in groups:
        lines += [
            "",
            "[[group]]",
            f"key = {toml_str(g['key'])}",
            f"area = {toml_str(g['area'])}",
            f"source = {toml_str(g['source'])}",
            f"count = {len(g['features'])}",
        ]
        for f in g["features"]:
            lines += [
                "",
                "[[group.feature]]",
                f"index = {f['index']}",
                f"name = {toml_str(f['name'])}",
                f"mobile = {toml_str(f['mobile'])}",
            ]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("json_path", type=Path, help="planning inventory JSON (workflow output or its result object)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"output TOML (default: {DEFAULT_OUT})")
    args = ap.parse_args(argv)

    raw = args.json_path.read_bytes()
    groups = build_groups(load_result(args.json_path))
    text = render(groups, args.json_path.name, hashlib.sha256(raw).hexdigest())

    try:  # validate the output when a TOML parser is available (3.11+)
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - Python 3.10
        tomllib = None
    if tomllib is not None:
        parsed = tomllib.loads(text)
        n = sum(len(g["feature"]) for g in parsed["group"])
        if n != parsed["total"]:
            raise SystemExit(f"internal error: parsed {n} features, expected {parsed['total']}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8", newline="\n")
    total = sum(len(g["features"]) for g in groups)
    print(f"wrote {args.out} ({len(groups)} groups, {total} features)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
